# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  param_fetcher_listener: force
  #    allowed_methods_listener:  true
  #    routing_loader: true
  serializer:
    serialize_null: true
  body_listener:
    enabled: true
    throw_exception_on_unsupported_content_type: true
    decoders:
      json: fos_rest.decoder.json
  view:
    view_response_listener: true
  #    exception:
  #        codes:
  #            App\Exception\MyException: 403
  #        messages:
  #            App\Exception\MyException: Forbidden area.
  format_listener:
    rules:
      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }