version: '3.1'

services:

  app:
    build: docker
    container_name: 'php-7.4'
    ports:
      - 9000:9000
    volumes:
      - ./:/app
    working_dir: /app

  nginx:
    image: nginx
    container_name: 'nginx-app'
    working_dir: /app
    ports:
      - 7777:80
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:12
    ports:
      - 15432:5432
    container_name: 'postgresql'
    working_dir: /app
    restart: always
    environment:
      POSTGRES_DB: 'app'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - dump:/app/dump
      - postgresql:/var/lib/postgresql/data

volumes:
  dump:
  postgresql: